# Generated by Django 3.1.7 on 2021-04-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBOTRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(default=None, max_length=100)),
                ('manager', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'DBOTRequest',
            },
        ),
    ]
